language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: PsULhG0afF1OQt4S/F+2aR00h1jXw871T0QAukERK6Yyct3trHvY3xW8ylHFDsZW2DJJismwvQSmSpZRsyeGe6e93f1VaytWVTpgiyFcubp4spkeKBoezgisR7XQ3ACD+v4umqYAbkXTtuLjf36kMknWk3Zu3+bwAJHALaBmNlNxrbI252N1H9Bd+QgdLv62kJNHsXlWfhWZueGwrDyWj8egk41OekYyTWnSdt4CFwTrcTBg2Xd+G1Ewb0mjUSwBM82fTJhgJppMWvjiEcrbI7VZviSBve/g4++k/S+0M/AS1v2YYXCbUH/OcSOJaS3YeKnyIAzHSr6bRKr2EiiHee/JYHeg5/EUZhtNk3IXTVZKkcchYdL+fFaErwbZyRGCyrVKlJWuzzaRSAc9nxesDJqxthhJbAcOt2vqpcIGcSEK6h8RmTkT1HU6VA0wVlhtfwzypMPZDnyqoe9MZodb2dl/iwFoZtVYkOFGrIa8ES/odAiYxwhg8CZObSyz82zW+Idx47UgQuiMoiQmpBm0LXA71Ce6Ibpr3+7FcrV1Hs4UFSnGCcr0/BWqdeRZojFxit9Z7hycQfV25qWWDPd3z61bs9YyO5gcaj+jEYgq4jQaPGn7k4FwyMbW1KdA/yWjWU8Jf5VvEzKvF5vBJ3JNTfZnIxmBp2q5tr1NL2PxoiA=
  app: salty-eyrie-10604
  on:
    repo: dafear/node-shopping-list-integration-tests
